### ISSUE TITLE
OpenAPIドキュメントの更新

### ISSUE THREAD

**Issue by itoshot** [Personal-Data-Linkage-Module/pxr-book-operate-service#7]
```[tasklist]
### Tasks
- [ ] POST /user
- [ ] POST /user/delete
- [x] POST /user/list
- [x] POST /event/{userId}
- [ ] PUT /event/{userId}
- [ ] PUT /event/{userId}/{eventId}
- [ ] DELETE /event/{userId}
- [ ] DELETE /event/{userId}/{eventId}
- [x] POST /thing/{userId}/{eventId}
- [ ] POST /thing/bulk/{userId}/{eventId}
- [ ] PUT /thing/{userId}/{eventId}
- [ ] PUT /thing/{userId}/{eventId}/{thingId}
- [ ] DELETE /thing/{userId}/{eventId}
- [ ] DELETE /thing/{userId}/{eventId}/{thingId}
- [x] POST /document/{userId}
- [ ] PUT /document/{userId}
- [ ] PUT /decument/{userId}/{documentId}
- [ ] DELETE /document/{userId}
- [ ] DELETE /document/{userId}/{documentId}
- [x] POST /share
- [ ] POST /share/temp
```
